### ISSUE TITLE
Installation or build not working

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/nativescript-vscode-extension#10]
NativeScript cannot be found as extension. Build is not working, webKitDebug.js cannot be found. Changed the name to webKitDebug.ts and then it said cannot be launch and that a possible solution is to set outDir ...

**Comment by ivanbuhov** [comment]
Hi @alexrainman 
The NativeScript extension cannot be found because it is not published in the VSCode Marketplace, yet. I guess you are following the build steps [here](https://github.com/NativeScript/nativescript-vscode-extension/blob/master/README.md), so make sure you have selected `launch in extension host` configuration from Debug panel, before pressing F5.

**Comment by alexrainman** [comment]
I get this error now: No handler found for the command: 'nativescript.build'. Ensure there is an activation event defined, if you are an extension.

**Comment by ivanbuhov** [comment]
Currently, only NativeScript Run command is actually working. The NativeScript extension for VSCode is in the process of active development. Currently, you can find such non-friendly messages. They will be fixed in the final version. 
FYI the build command may be removed in the future. We will keep a minimalistic list of commands in the Command Palette.

**Comment by alexrainman** [comment]
Run is not working neither. No handler found for the command: 'nativescript.run'. Ensure there is an activation event defined, if you are an extension.
<img width="289" alt="screen shot 2016-02-02 at 9 04 31 am" src="https://cloud.githubusercontent.com/assets/3793554/12753292/13b93e1c-c98c-11e5-8ab1-c34e108731cf.png">

**Comment by ivanbuhov** [comment]
How do you launch the extension - `as server` or `in extension host`. Commands should work in extension host, only.

**Comment by alexrainman** [comment]
in extension host

**Comment by ivanbuhov** [comment]
Updated the build steps (https://github.com/NativeScript/nativescript-vscode-extension/commit/f791b484bf620e5c7e19ba471726c0fcf48f127a). Make sure you have run `gulp` command in the extension folder.

**Comment by alexrainman** [comment]
Its working now. Please, update your build steps ;)

**Comment by alexrainman** [comment]
Are you planning to integrate debuging and code hints?

**Comment by alexrainman** [comment]
And other commands like add platform, modules and plugins? Create project?

**Comment by ivanbuhov** [comment]
Debugging is already implemented but to make it work you have to [package and install the extension](https://code.visualstudio.com/docs/tools/vscecli#_packaging-extensions). After that, open VSCode, go to Debug Panel and click the little gear icon next to the select box and select NativeScript from the list. Now you can choose a configuration from the list and press Start. Bare in mind that debugging on physical iOS device is currently not working but you can try the other options. 
With regard to the commands, we will add only `NativeScript Run` in v1.0. Since VSCode is not supposed to be an IDE we prefer exposing a short list of helpful and often used commands instead of providing full IDE experience. Generally, `tns platform add` and `tns project create` are executed once per project so we prefer not adding them in the Command Palette.
