### ISSUE TITLE
0.5.0 [Linux] Extension Crashes On Debug

### ISSUE THREAD

**Issue by rLoka** [NativeScript/nativescript-vscode-extension#100]
Hey,

I updated VS extension to the newest version (0.4.5), and since then, I cannot debug or lunch from VS itself, however, I can tns debug or tns livesync normally.

This is the following error:
Debug adapter process has terminated unexpectedly

**Comment by ivanbuhov** [comment]
@rLoka I guess you mean v0.5.0.
Delete your `launch.json` file from `.vscode` folder and regenerate it again. If this doesn't help set `diagnsoticLogging` flag to `true` in the debug configuration in `launch.json` and run it again. Send us the whole output printed in the debugger console.

**Comment by rLoka** [comment]
There is no output when clicked on "Lunch on Android", just this message. I am working on Ubuntu 16.10.
![screenshot from 2016-12-08 17-23-49](https://cloud.githubusercontent.com/assets/9071942/21017886/20748016-bd6b-11e6-93f4-7c42749da34c.png)

**Comment by ivanbuhov** [comment]
@rLoka The issue is [fixed](https://github.com/NativeScript/nativescript-vscode-extension/commit/628b06732076feee074803f95c38b76c9a118f35) in the `master` branch. We are going to release a hotfix of the extension. 

Till then you can use this package: [nativescript-0.5.0.vsix.zip](https://github.com/NativeScript/nativescript-vscode-extension/files/641710/nativescript-0.5.0.vsix.zip) which contains the desired fix. To install it:
1. Extract the `.zip` containing the `.vsix` package.
2. From VS Code Command Pallete run `Extensions: Install from VSIX...` command (type `vsix` in the Command Pallete input box to find it) and select the downloaded `.vsix` package.
