### ISSUE TITLE
VS Code Debugger Not Attaching On iOS Emulator

### ISSUE THREAD

**Issue by burkeholland** [NativeScript/nativescript-vscode-extension#35]
After upgrading to NativeScript 1.7, the debugger now terminates immediately in my application when I try to run it on the iOS emulator.

### Steps to reproduce

1. `tns create sample-app && cd sample-app`
2. `tns platform add ios`
3. `tns deploy ios --emulator`
4. `code .`
5. Configure NativeScript debugger
6. Select `Launch on Emulator` from Debugger menu
7. Click the "run" icon

Console output...

Starting iOS Simulator
Setting up proxy...
Press Ctrl + C to terminate, or disconnect.
socket-file-location: /var/folders/ck/9fcxhx1d46q9qlglpk2l4tb80000gn/T/116218-18244-1c8atc1.sock
Suppressing debugging client.
Frontend client connected.
Backend socket created.
Error: read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TCP.onread (net.js:544:26)
Sending exception report (press Ctrl+C to stop)...
Terminating debug session
Closing debug connection

### System Information

NativeScript 1.7
iOS 9.2
Xcode 7.2.1

**Comment by burkeholland** [comment]
After the NativeScript CLI 1.7 upgrade, I had to `npm remove -g nativscript` and `npm install -g nativescript`. The debugger is working again.

**Comment by Anilinfo2015** [comment]
not working for me.

**Comment by ivanbuhov** [comment]
@Anilinfo2015 Can you specify you NativeScript CLI/iOS/Xcode versions? Is the output the same as in the original issue? Is it reproduced in a brand new project?

**Comment by Anilinfo2015** [comment]
Hi, @Ivanbuhov, thanks for replied 
There are multiple issue i face during $tns run 

Android : v23
TNS : latest(2.1.1)
Node : 4.4
Platform : android 

(1) /node_modules copies very slowly to /tns_modules while build cycle. I have even reinstalled my OS 7 due to this.
(2) After building app first time second time build/run it take very long time to execute Hooks(20-30 minutes). I have followed standard commands guide.

Thanks for your kind reply.

**Comment by ivanbuhov** [comment]
Hi @Anilinfo2015, as far as I can understand, your problem is not related to the original issue (`VS Code Debugger Not Attaching On iOS Emulator`) so creating a new issue for your problem will make easier for other people with the same issue to find it. You can post link to this discussion in the newly created issue.

Unfortunately, I can't reproduce the issue (provide`steps to reproduce` if possible). Try to build/run/debug the app directly using the CLI in the command prompt (`tns debug android`, `tns run android`). Is it so slow again?

**Comment by Anilinfo2015** [comment]
Ok, i will create new issue yes it is still slow. even though i have reinstall my OS windows 7.
